### ISSUE TITLE
'OverDrive8' object has no attribute

### ISSUE THREAD

**Issue by JustUsers** [kdschlosser/ati_radeon#2]
My friend has an AMD Radeon RX 5700, this is the result

<details>
  <summary>result (click to show)</summary>

```
id: 390025672
name: AMD Radeon RX 5700
index: 0
device_number: 0
bus_number: 5
vendor_id: 1002
supports_edid_management: False
is_overdrive_enabled: True
is_overdrive_supported: True
overdrive_version: 8
supported_aspects: ['Radeon3D', 'DisplaysColour2,DisplaysColour', 'DisplaysManager', 'DisplaysOptions', 'DeviceCRT2', 'DeviceLCD2', 'DeviceDFP2', 'MMVideo']
udid: PCI_VEN_1002&DEV_731F&SUBSYS_AA021E7B&REV_C4_6&1B20E12F&0&000000E7A
function_number: 0
is_present: True
exists: True
driver_path: \Registry\Machine\System\CurrentControlSet\Control\Video\{1F3F4DD1-B2DC-11EA-B2A0-B8975AF1B74D}\0000
driver_path_ext: {4d36e968-e325-11ce-bfc1-08002be10318}\0002
upnp_path: PCI\VEN_1002&DEV_731F&SUBSYS_AA021E7B&REV_C4\6&1B20E12F&0&000000E7
display_index: 3
driver_index: None
screen_config_name: None
asic_family_type: Discrete
can_change_speed: False
speed: Unforced
default_speed: Unforced
is_gpu_accessable: False

Traceback (most recent call last):
  File "D:\PY\ati_radeon-master\example.py", line 57, in <module>
    print('is_power_control_supported:', adapter.is_power_control_supported)
  File "D:\PY\ati_radeon-master\pyamd_adl\adapter_h.py", line 2652, in is_power_control_supported
    return overdrive.is_power_control_supported
AttributeError: 'OverDrive8' object has no attribute 'is_power_control_supported'
```
</details>

**Comment by kdschlosser** [comment]
again I have not completed all of the overdrive classes that span all versions of overdrive.

overdrive 5 and 7 are completed. I have to work the ret of the kinks out of 7 (this is what you have)
If you will have access to your friends setup and can run the example on that machine I can also walk through the overdrive 8 stuff as well.
