### ISSUE TITLE
Support for RTX 7900 XTX?

### ISSUE THREAD

**Issue by xhemp** [kdschlosser/ati_radeon#3]
Greetings!

Just tried to run example on a 7900 XTX but looks like it has Overdrive 8 and I believe it hasn't been implemented yet?

```
id: -30560160
name: AMD Radeon RX 7900 XTX
index: 0
device_number: 0
bus_number: 10
vendor_id: 1002
supports_edid_management: True
is_overdrive_enabled: True
is_overdrive_supported: True
overdrive_version: 8
supported_aspects: ['Radeon3D', 'DisplaysColour2,DisplaysColour', 'DisplaysManager', 'DisplaysOptions', 'DeviceCRT2', 'DeviceLCD2', 'DeviceDFP2', 'MMVideo']
udid: PCI_VEN_1002&DEV_744C&SUBSYS_240E1458&REV_C8_6&199C31A0&0&00000019A
function_number: 0
is_present: True
exists: True
driver_path: \Registry\Machine\System\CurrentControlSet\Control\Video\{AE70691F-877F-11ED-A080-806E6F6E6963}\0000
driver_path_ext: {4d36e968-e325-11ce-bfc1-08002be10318}\0001
upnp_path: PCI\VEN_1002&DEV_744C&SUBSYS_240E1458&REV_C8\6&199C31A0&0&00000019
display_index: 0
driver_index: None
screen_config_name: None
asic_family_type: Discrete
can_change_speed: False
speed: Unforced
default_speed: Unforced
is_gpu_accessable: False
Traceback (most recent call last):
  File "C:\Users\xhemp\temp\ati_radeon\example.py", line 60, in <module>
    print('is_power_control_supported:', adapter.is_power_control_supported)
  File "C:\Users\xhemp\temp\ati_radeon\pyamd_adl\adapter_h.py", line 2656, in is_power_control_supported
    return overdrive.is_power_control_supported
  File "C:\Users\xhemp\temp\ati_radeon\pyamd_adl\overdrive8_h.py", line 1729, in is_power_control_supported
    _ADL2_Overdrive8_Init_SettingX2_Get(
  File "C:\Users\xhemp\temp\ati_radeon\pyamd_adl\adl_structures_h.py", line 4458, in __call__
    res = func(*params)
```

I understand this hasn't been updated in a while but thought I would give it a shot but it's cool if you are not on it anymore, though.

**Comment by kdschlosser** [comment]
I can mess around with it again but I will have to see if my Nvidia Quadro RTX 4000 will play nice nice with an ATI video card installed I to the same machine.

Sometimes they won't

**Comment by xhemp** [comment]
Good stuff. I've seen your comments trying to get answers from AMD and not having much help. Looks like the feeling is unanimous as I can't find anyone that was able to get through them. There's this guy here,though,  at 3dguru.com that has an app that actually works with my card, even though he's not active anymore (last logged in there years ago)
Don't know if that helps:

https://forums.guru3d.com/threads/overdriventool-tool-for-amd-gpus.416116/
